model_name: 'proxy_model_race_income_adult'

#------------load dataset------------------------
input_data: 'adult_binary.csv'
data_type: 'adult' #choose between ['adult','ipums']
load_data:
  select_columns:  #parameters to select the columns to read
    use_features:
        #####-----change here-------### should be written exactly as is in the dataset
      - 'age'
      - 'education-num'
      - 'marital-status'
      - 'occupation'
        #####-----------------------###
      - 'race'
      - 'sex'
      - 'rich'
  load_params: null


sample_size: null  #sample size during selection of training set
features:
  AGE : null
  RACE : 'race'
  SEX : 'sex'


#-------------model parameters-----------------------
pg_target: 'black'
rai_target: 'rich'
threshold_rai_target: 0.8
bias_ranker:
  pos_rate: 0.2
  bias_tolerance: 0.2
latest_year_dataset: 2020
random_state_sample: 42

#-------------binary model parameters--------------------
model:
  name: 'LGBMClassifier'
  params:
    max_depth: 3
    n_estimators: 1000
    objective: "binary"
  training_params:
    early_stopping_rounds: 100
    verbose: 100
  grid_search:
    n_estimators: [100, 200, 400]
    max_depth: [4, 6, 8, 10]
test_cutoff: 0.8
split_random_size: 42