model_name: 'proxy_model_race_income_ipums_reduced'   #####-----change here-------###

#------------load dataset------------------------
input_data: 'usa_IPUMS_2022.csv.gz'   #####-----change here-------###
data_type: 'ipums' #choose between ['adult','ipums']  #####-----change here-------###
load_data:
  select_columns:  #parameters to select the columns to read
    use_features:
        #####-----change here-------### should be written exactly as is in the dataset
      - 'AGE'
#      - 'EDUC'
#      - 'MARST'
      - 'SEX'
        #####-----------------------###
      - 'RACE'
      - 'HISPAN' #we need this for hispanic dataset
      - 'INCTOT'
      - 'YEAR'
      - 'MET2013'
  load_params: #dataset loading parameters
    compression: 'gzip'
    header: 0
    sep: ','
    quotechar: '"'
    error_bad_lines: False


sample_size: 200000  #sample size during selection of training set
features:
  AGE: 'age'
  RACE: 'race'
  SEX: 'sex'
  INCTOT: 'inctot' #
  YEAR: 'year'
  MET2013: 'met2013'  #2013 US Census metropolitan area
  RENT: 'rent'
  MORTGAGE: 'mortgage'
  EDUC: 'educ'  #educated
  MARST: 'marst'  #Marital status


#-------------model parameters-----------------------
pg_target: 'hispanic'
rai_target: 'inctot'
threshold_rai_target: 0.8
bias_ranker:
  pos_rate: 0.2
  bias_tolerance: 0.2
latest_year_dataset: 2020
random_state_sample: 42

#-------------binary model parameters--------------------
model:
  name: 'LGBMClassifier'
  params:
    max_depth: 3
    n_estimators: 1000
    objective: "binary"
  training_params:
    early_stopping_rounds: 100
    verbose: 100
  grid_search:
    n_estimators: [100, 200, 400]
    max_depth: [4, 6, 8, 10]
test_cutoff: 0.8
split_random_size: 42